# Generated by Django 4.2.3 on 2023-07-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptodo', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MIDL', 'MIDL'), ('LOW', 'LOW')], default='LOW', max_length=50),
        ),
    ]
